name: build
on: push
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-user qemu-user-static
      - name: bazel cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/bazel
          key: bazel
      - name: build and test
        env:
          DOCKER_BUILDKIT: 1
        run: |
          docker build \
            --cache-from discolix/build \
            --build-arg BUILDKIT_INLINE_CACHE=1 \
            --target build -t discolix/build -f tools/docker/Dockerfile .
          tools/ci/bazel.sh test //...
      - name: publish
        if: github.ref == 'refs/heads/master'
        env:
          PROJECT_GIT_COMMIT: ${{ github.sha }}
          REGISTRY_USER: ${{ secrets.DockerHubUser }}
          REGISTRY_PASS: ${{ secrets.DockerHubToken }}
        run: tools/ci/publish.sh
