name: check-debs
on:
  schedule:
    - cron: "0 20 * * *"
jobs:
  check:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Bazel build-cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/bazel
          key: bazel
      - name: Check for bad urls
        env:
          DEB_CHECKER_NOTIFIERS: ${{ secrets.DEB_CHECKER_NOTIFIERS }}
        run: tools/ci/bazel.sh run //tools/deb_checker
      - name: Bazel build-cache permissions
        run: sudo chmod -R +rwx ~/.cache/bazel
